version: '3.1'
services:
  mysql:
    build:
      context: .
      dockerfile: DockerFile.mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - '3306:3306'
#    volumes:
#      - "./my.cnf:/etc/mysql/conf.d/my.cnf"
#      - "./init_mysql:/docker-entrypoint-initdb.d"